name: ci

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  ORGANIZATION: ali1416
  PROJECT_KEY: ALI1416_$GITHUB_ACTOR

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -P jacoco

    - name: aaa
      run: echo "$GITHUB_ACTOR"

    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@v1.9
      with:
        args:
          -Dsonar.organization=$ORGANIZATION
          -Dsonar.projectKey=$PROJECT_KEY

    - name: Send coverage report to SonarCloud
    run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$ORGANIZATION -Dsonar.projectKey=$PROJECT_KEY -Dsonar.login=$SONAR_TOKEN
